name: 'GitHub notice to Slack'
description:
  'This workflow is triggered by the opening of a pull request and notifies
  users assigned as reviewers via mention on Slack.'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
